import type { TimelineItem, AcademicYear, StudentType } from '@/types/timeline';

// Generate unique IDs for timeline items
const generateId = (year: string, type: string, index: number) =>
  `${year}-${type}-${index}`;

export const timelineDatabase: Record<AcademicYear, Record<StudentType, TimelineItem[]>> = {
  '2025-26': {
    'high-school': [
      {
        id: generateId('2025', 'hs', 1),
        date: '2024-10-01',
        title: 'FAFSA Opens',
        description: 'The 2025-26 FAFSA becomes available. This is the earliest you can submit your application for maximum aid consideration.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2025', 'hs', 2),
        date: '2024-11-01',
        title: 'Priority Deadline - Many States',
        description: 'Submit FAFSA by this date for maximum state aid consideration. Check your state\'s specific deadline as some states have earlier dates.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2025', 'hs', 3),
        date: '2024-12-01',
        title: 'Priority Deadline - Many Colleges',
        description: 'Submit FAFSA by this date for maximum institutional aid consideration. Early submission increases your chances of receiving more aid.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2025', 'hs', 4),
        date: '2025-01-01',
        title: 'Tax Documents Available',
        description: 'Gather your 2023 tax documents and W-2s. Use the IRS Data Retrieval Tool for accuracy and faster processing.',
        type: 'priority',
        priority: true,
      },
      {
        id: generateId('2025', 'hs', 5),
        date: '2025-02-01',
        title: 'State Aid Deadlines',
        description: 'Many states have February 1st deadlines for state grants and scholarships. Don\'t miss out on free money!',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2025', 'hs', 6),
        date: '2025-03-01',
        title: 'College Aid Deadlines',
        description: 'Most colleges have March 1st deadlines for institutional aid. Verify specific deadlines for your target schools.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2025', 'hs', 7),
        date: '2025-04-01',
        title: 'Award Letters Arrive',
        description: 'Colleges begin sending financial aid award letters. Compare packages carefully to understand your true cost.',
        type: 'priority',
        priority: false,
      },
      {
        id: generateId('2025', 'hs', 8),
        date: '2025-05-01',
        title: 'National Decision Day',
        description: 'Deadline to accept admission offers and submit enrollment deposits. This is your final decision day!',
        type: 'deadline',
        priority: true,
      },
    ],
    'current-college': [
      {
        id: generateId('2025', 'cc', 1),
        date: '2024-10-01',
        title: 'FAFSA Opens',
        description: 'The 2025-26 FAFSA becomes available. Renew your application early for best aid packages.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2025', 'cc', 2),
        date: '2024-11-01',
        title: 'Priority Deadline',
        description: 'Submit FAFSA by this date for maximum aid consideration. Renewal applications are processed faster when submitted early.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2025', 'cc', 3),
        date: '2025-01-01',
        title: 'Tax Documents Available',
        description: 'Gather your 2023 tax documents. Use IRS Data Retrieval Tool for accuracy.',
        type: 'priority',
        priority: true,
      },
      {
        id: generateId('2025', 'cc', 4),
        date: '2025-03-01',
        title: 'College Aid Deadlines',
        description: 'Most colleges have March 1st deadlines for institutional aid renewals.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2025', 'cc', 5),
        date: '2025-04-01',
        title: 'Award Letters Arrive',
        description: 'Your college will send your financial aid award letter for the upcoming year.',
        type: 'priority',
        priority: false,
      },
    ],
    'graduate': [
      {
        id: generateId('2025', 'grad', 1),
        date: '2024-09-01',
        title: 'Graduate School Financial Aid Research',
        description: 'Research graduate school financial aid options including assistantships, fellowships, and research grants.',
        type: 'priority',
        priority: true,
      },
      {
        id: generateId('2025', 'grad', 2),
        date: '2024-10-01',
        title: 'FAFSA Opens',
        description: 'The 2025-26 FAFSA becomes available. Graduate students can access federal loans and work-study.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2025', 'grad', 3),
        date: '2024-12-01',
        title: 'Graduate School Applications',
        description: 'Submit graduate school applications with financial aid considerations. Many programs have rolling admissions.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2025', 'grad', 4),
        date: '2025-03-01',
        title: 'Assistantship Applications Due',
        description: 'Many graduate programs have March deadlines for teaching and research assistantships.',
        type: 'deadline',
        priority: true,
      },
    ],
    'adult-learner': [
      {
        id: generateId('2025', 'adult', 1),
        date: '2024-08-01',
        title: 'Adult Learner Financial Aid Research',
        description: 'Research adult learner specific financial aid programs and employer tuition assistance.',
        type: 'priority',
        priority: true,
      },
      {
        id: generateId('2025', 'adult', 2),
        date: '2024-09-01',
        title: 'Employer Tuition Assistance',
        description: 'Apply for employer tuition assistance programs if available. Many companies offer education benefits.',
        type: 'priority',
        priority: true,
      },
      {
        id: generateId('2025', 'adult', 3),
        date: '2024-10-01',
        title: 'FAFSA Opens',
        description: 'The 2025-26 FAFSA becomes available. Adult learners may qualify for independent student status.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2025', 'adult', 4),
        date: '2024-11-01',
        title: 'Priority Deadline',
        description: 'Submit FAFSA early for maximum aid. Adult learners have access to Pell Grants and federal loans.',
        type: 'deadline',
        priority: true,
      },
    ],
  },
  '2026-27': {
    'high-school': [
      {
        id: generateId('2026', 'hs', 1),
        date: '2025-10-01',
        title: 'FAFSA Opens',
        description: 'The 2026-27 FAFSA becomes available. This is the earliest you can submit your application for maximum aid consideration.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2026', 'hs', 2),
        date: '2025-11-01',
        title: 'Priority Deadline - Many States',
        description: 'Submit FAFSA by this date for maximum state aid consideration. Check your state\'s specific deadline as some states have earlier dates.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2026', 'hs', 3),
        date: '2025-12-01',
        title: 'Priority Deadline - Many Colleges',
        description: 'Submit FAFSA by this date for maximum institutional aid consideration. Early submission increases your chances of receiving more aid.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2026', 'hs', 4),
        date: '2026-01-01',
        title: 'Tax Documents Available',
        description: 'Gather your 2024 tax documents and W-2s. Use the IRS Data Retrieval Tool for accuracy and faster processing.',
        type: 'priority',
        priority: true,
      },
      {
        id: generateId('2026', 'hs', 5),
        date: '2026-02-01',
        title: 'State Aid Deadlines',
        description: 'Many states have February 1st deadlines for state grants and scholarships. Don\'t miss out on free money!',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2026', 'hs', 6),
        date: '2026-03-01',
        title: 'College Aid Deadlines',
        description: 'Most colleges have March 1st deadlines for institutional aid. Verify specific deadlines for your target schools.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2026', 'hs', 7),
        date: '2026-04-01',
        title: 'Award Letters Arrive',
        description: 'Colleges begin sending financial aid award letters. Compare packages carefully to understand your true cost.',
        type: 'priority',
        priority: false,
      },
      {
        id: generateId('2026', 'hs', 8),
        date: '2026-05-01',
        title: 'National Decision Day',
        description: 'Deadline to accept admission offers and submit enrollment deposits. This is your final decision day!',
        type: 'deadline',
        priority: true,
      },
    ],
    'current-college': [
      {
        id: generateId('2026', 'cc', 1),
        date: '2025-10-01',
        title: 'FAFSA Opens',
        description: 'The 2026-27 FAFSA becomes available. Renew your application early for best aid packages.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2026', 'cc', 2),
        date: '2025-11-01',
        title: 'Priority Deadline',
        description: 'Submit FAFSA by this date for maximum aid consideration. Renewal applications are processed faster when submitted early.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2026', 'cc', 3),
        date: '2026-01-01',
        title: 'Tax Documents Available',
        description: 'Gather your 2024 tax documents. Use IRS Data Retrieval Tool for accuracy.',
        type: 'priority',
        priority: true,
      },
      {
        id: generateId('2026', 'cc', 4),
        date: '2026-03-01',
        title: 'College Aid Deadlines',
        description: 'Most colleges have March 1st deadlines for institutional aid renewals.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2026', 'cc', 5),
        date: '2026-04-01',
        title: 'Award Letters Arrive',
        description: 'Your college will send your financial aid award letter for the upcoming year.',
        type: 'priority',
        priority: false,
      },
    ],
    'graduate': [
      {
        id: generateId('2026', 'grad', 1),
        date: '2025-09-01',
        title: 'Graduate School Financial Aid Research',
        description: 'Research graduate school financial aid options including assistantships, fellowships, and research grants.',
        type: 'priority',
        priority: true,
      },
      {
        id: generateId('2026', 'grad', 2),
        date: '2025-10-01',
        title: 'FAFSA Opens',
        description: 'The 2026-27 FAFSA becomes available. Graduate students can access federal loans and work-study.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2026', 'grad', 3),
        date: '2025-12-01',
        title: 'Graduate School Applications',
        description: 'Submit graduate school applications with financial aid considerations. Many programs have rolling admissions.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2026', 'grad', 4),
        date: '2026-03-01',
        title: 'Assistantship Applications Due',
        description: 'Many graduate programs have March deadlines for teaching and research assistantships.',
        type: 'deadline',
        priority: true,
      },
    ],
    'adult-learner': [
      {
        id: generateId('2026', 'adult', 1),
        date: '2025-08-01',
        title: 'Adult Learner Financial Aid Research',
        description: 'Research adult learner specific financial aid programs and employer tuition assistance.',
        type: 'priority',
        priority: true,
      },
      {
        id: generateId('2026', 'adult', 2),
        date: '2025-09-01',
        title: 'Employer Tuition Assistance',
        description: 'Apply for employer tuition assistance programs if available. Many companies offer education benefits.',
        type: 'priority',
        priority: true,
      },
      {
        id: generateId('2026', 'adult', 3),
        date: '2025-10-01',
        title: 'FAFSA Opens',
        description: 'The 2026-27 FAFSA becomes available. Adult learners may qualify for independent student status.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2026', 'adult', 4),
        date: '2025-11-01',
        title: 'Priority Deadline',
        description: 'Submit FAFSA early for maximum aid. Adult learners have access to Pell Grants and federal loans.',
        type: 'deadline',
        priority: true,
      },
    ],
  },
  '2027-28': {
    'high-school': [
      {
        id: generateId('2027', 'hs', 1),
        date: '2026-10-01',
        title: 'FAFSA Opens',
        description: 'The 2027-28 FAFSA becomes available. This is the earliest you can submit your application for maximum aid consideration.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2027', 'hs', 2),
        date: '2026-11-01',
        title: 'Priority Deadline - Many States',
        description: 'Submit FAFSA by this date for maximum state aid consideration. Check your state\'s specific deadline as some states have earlier dates.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2027', 'hs', 3),
        date: '2026-12-01',
        title: 'Priority Deadline - Many Colleges',
        description: 'Submit FAFSA by this date for maximum institutional aid consideration. Early submission increases your chances of receiving more aid.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2027', 'hs', 4),
        date: '2027-01-01',
        title: 'Tax Documents Available',
        description: 'Gather your 2025 tax documents and W-2s. Use the IRS Data Retrieval Tool for accuracy and faster processing.',
        type: 'priority',
        priority: true,
      },
      {
        id: generateId('2027', 'hs', 5),
        date: '2027-02-01',
        title: 'State Aid Deadlines',
        description: 'Many states have February 1st deadlines for state grants and scholarships. Don\'t miss out on free money!',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2027', 'hs', 6),
        date: '2027-03-01',
        title: 'College Aid Deadlines',
        description: 'Most colleges have March 1st deadlines for institutional aid. Verify specific deadlines for your target schools.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2027', 'hs', 7),
        date: '2027-04-01',
        title: 'Award Letters Arrive',
        description: 'Colleges begin sending financial aid award letters. Compare packages carefully to understand your true cost.',
        type: 'priority',
        priority: false,
      },
      {
        id: generateId('2027', 'hs', 8),
        date: '2027-05-01',
        title: 'National Decision Day',
        description: 'Deadline to accept admission offers and submit enrollment deposits. This is your final decision day!',
        type: 'deadline',
        priority: true,
      },
    ],
    'current-college': [
      {
        id: generateId('2027', 'cc', 1),
        date: '2026-10-01',
        title: 'FAFSA Opens',
        description: 'The 2027-28 FAFSA becomes available. Renew your application early for best aid packages.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2027', 'cc', 2),
        date: '2026-11-01',
        title: 'Priority Deadline',
        description: 'Submit FAFSA by this date for maximum aid consideration. Renewal applications are processed faster when submitted early.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2027', 'cc', 3),
        date: '2027-01-01',
        title: 'Tax Documents Available',
        description: 'Gather your 2025 tax documents. Use IRS Data Retrieval Tool for accuracy.',
        type: 'priority',
        priority: true,
      },
      {
        id: generateId('2027', 'cc', 4),
        date: '2027-03-01',
        title: 'College Aid Deadlines',
        description: 'Most colleges have March 1st deadlines for institutional aid renewals.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2027', 'cc', 5),
        date: '2027-04-01',
        title: 'Award Letters Arrive',
        description: 'Your college will send your financial aid award letter for the upcoming year.',
        type: 'priority',
        priority: false,
      },
    ],
    'graduate': [
      {
        id: generateId('2027', 'grad', 1),
        date: '2026-09-01',
        title: 'Graduate School Financial Aid Research',
        description: 'Research graduate school financial aid options including assistantships, fellowships, and research grants.',
        type: 'priority',
        priority: true,
      },
      {
        id: generateId('2027', 'grad', 2),
        date: '2026-10-01',
        title: 'FAFSA Opens',
        description: 'The 2027-28 FAFSA becomes available. Graduate students can access federal loans and work-study.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2027', 'grad', 3),
        date: '2026-12-01',
        title: 'Graduate School Applications',
        description: 'Submit graduate school applications with financial aid considerations. Many programs have rolling admissions.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2027', 'grad', 4),
        date: '2027-03-01',
        title: 'Assistantship Applications Due',
        description: 'Many graduate programs have March deadlines for teaching and research assistantships.',
        type: 'deadline',
        priority: true,
      },
    ],
    'adult-learner': [
      {
        id: generateId('2027', 'adult', 1),
        date: '2026-08-01',
        title: 'Adult Learner Financial Aid Research',
        description: 'Research adult learner specific financial aid programs and employer tuition assistance.',
        type: 'priority',
        priority: true,
      },
      {
        id: generateId('2027', 'adult', 2),
        date: '2026-09-01',
        title: 'Employer Tuition Assistance',
        description: 'Apply for employer tuition assistance programs if available. Many companies offer education benefits.',
        type: 'priority',
        priority: true,
      },
      {
        id: generateId('2027', 'adult', 3),
        date: '2026-10-01',
        title: 'FAFSA Opens',
        description: 'The 2027-28 FAFSA becomes available. Adult learners may qualify for independent student status.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2027', 'adult', 4),
        date: '2026-11-01',
        title: 'Priority Deadline',
        description: 'Submit FAFSA early for maximum aid. Adult learners have access to Pell Grants and federal loans.',
        type: 'deadline',
        priority: true,
      },
    ],
  },
  '2028-29': {
    'high-school': [
      {
        id: generateId('2028', 'hs', 1),
        date: '2027-10-01',
        title: 'FAFSA Opens',
        description: 'The 2028-29 FAFSA becomes available. This is the earliest you can submit your application for maximum aid consideration.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2028', 'hs', 2),
        date: '2027-11-01',
        title: 'Priority Deadline - Many States',
        description: 'Submit FAFSA by this date for maximum state aid consideration. Check your state\'s specific deadline as some states have earlier dates.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2028', 'hs', 3),
        date: '2027-12-01',
        title: 'Priority Deadline - Many Colleges',
        description: 'Submit FAFSA by this date for maximum institutional aid consideration. Early submission increases your chances of receiving more aid.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2028', 'hs', 4),
        date: '2028-01-01',
        title: 'Tax Documents Available',
        description: 'Gather your 2026 tax documents and W-2s. Use the IRS Data Retrieval Tool for accuracy and faster processing.',
        type: 'priority',
        priority: true,
      },
      {
        id: generateId('2028', 'hs', 5),
        date: '2028-02-01',
        title: 'State Aid Deadlines',
        description: 'Many states have February 1st deadlines for state grants and scholarships. Don\'t miss out on free money!',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2028', 'hs', 6),
        date: '2028-03-01',
        title: 'College Aid Deadlines',
        description: 'Most colleges have March 1st deadlines for institutional aid. Verify specific deadlines for your target schools.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2028', 'hs', 7),
        date: '2028-04-01',
        title: 'Award Letters Arrive',
        description: 'Colleges begin sending financial aid award letters. Compare packages carefully to understand your true cost.',
        type: 'priority',
        priority: false,
      },
      {
        id: generateId('2028', 'hs', 8),
        date: '2028-05-01',
        title: 'National Decision Day',
        description: 'Deadline to accept admission offers and submit enrollment deposits. This is your final decision day!',
        type: 'deadline',
        priority: true,
      },
    ],
    'current-college': [
      {
        id: generateId('2028', 'cc', 1),
        date: '2027-10-01',
        title: 'FAFSA Opens',
        description: 'The 2028-29 FAFSA becomes available. Renew your application early for best aid packages.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2028', 'cc', 2),
        date: '2027-11-01',
        title: 'Priority Deadline',
        description: 'Submit FAFSA by this date for maximum aid consideration. Renewal applications are processed faster when submitted early.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2028', 'cc', 3),
        date: '2028-01-01',
        title: 'Tax Documents Available',
        description: 'Gather your 2026 tax documents. Use IRS Data Retrieval Tool for accuracy.',
        type: 'priority',
        priority: true,
      },
      {
        id: generateId('2028', 'cc', 4),
        date: '2028-03-01',
        title: 'College Aid Deadlines',
        description: 'Most colleges have March 1st deadlines for institutional aid renewals.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2028', 'cc', 5),
        date: '2028-04-01',
        title: 'Award Letters Arrive',
        description: 'Your college will send your financial aid award letter for the upcoming year.',
        type: 'priority',
        priority: false,
      },
    ],
    'graduate': [
      {
        id: generateId('2028', 'grad', 1),
        date: '2027-09-01',
        title: 'Graduate School Financial Aid Research',
        description: 'Research graduate school financial aid options including assistantships, fellowships, and research grants.',
        type: 'priority',
        priority: true,
      },
      {
        id: generateId('2028', 'grad', 2),
        date: '2027-10-01',
        title: 'FAFSA Opens',
        description: 'The 2028-29 FAFSA becomes available. Graduate students can access federal loans and work-study.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2028', 'grad', 3),
        date: '2027-12-01',
        title: 'Graduate School Applications',
        description: 'Submit graduate school applications with financial aid considerations. Many programs have rolling admissions.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2028', 'grad', 4),
        date: '2028-03-01',
        title: 'Assistantship Applications Due',
        description: 'Many graduate programs have March deadlines for teaching and research assistantships.',
        type: 'deadline',
        priority: true,
      },
    ],
    'adult-learner': [
      {
        id: generateId('2028', 'adult', 1),
        date: '2027-08-01',
        title: 'Adult Learner Financial Aid Research',
        description: 'Research adult learner specific financial aid programs and employer tuition assistance.',
        type: 'priority',
        priority: true,
      },
      {
        id: generateId('2028', 'adult', 2),
        date: '2027-09-01',
        title: 'Employer Tuition Assistance',
        description: 'Apply for employer tuition assistance programs if available. Many companies offer education benefits.',
        type: 'priority',
        priority: true,
      },
      {
        id: generateId('2028', 'adult', 3),
        date: '2027-10-01',
        title: 'FAFSA Opens',
        description: 'The 2028-29 FAFSA becomes available. Adult learners may qualify for independent student status.',
        type: 'deadline',
        priority: true,
      },
      {
        id: generateId('2028', 'adult', 4),
        date: '2027-11-01',
        title: 'Priority Deadline',
        description: 'Submit FAFSA early for maximum aid. Adult learners have access to Pell Grants and federal loans.',
        type: 'deadline',
        priority: true,
      },
    ],
  },
};

// State-specific additional timeline items
export const getStateSpecificItems = (state: string, academicYear: AcademicYear): TimelineItem[] => {
  const [startYear] = academicYear.split('-');
  const endYear = `20${academicYear.split('-')[1]}`;

  const stateItems: Record<string, TimelineItem[]> = {
    'CA': [
      {
        id: `${academicYear}-ca-1`,
        date: `${endYear}-03-02`,
        title: 'California Dream Act Application (CADAA)',
        description: 'If you are undocumented or DACA, complete the California Dream Act Application for state financial aid.',
        type: 'deadline',
        priority: true,
      },
    ],
    'TX': [
      {
        id: `${academicYear}-tx-1`,
        date: `${endYear}-01-15`,
        title: 'Texas Application for State Financial Aid (TASFA)',
        description: 'If you are undocumented or DACA, complete the TASFA for Texas state financial aid.',
        type: 'deadline',
        priority: true,
      },
    ],
    'NY': [
      {
        id: `${academicYear}-ny-1`,
        date: `${endYear}-06-30`,
        title: 'New York State Tuition Assistance Program (TAP)',
        description: 'Complete the TAP application for New York state financial aid.',
        type: 'deadline',
        priority: true,
      },
    ],
  };

  return stateItems[state] || [];
};

// Special circumstances timeline items
export const getSpecialCircumstancesItems = (
  circumstances: any,
  academicYear: AcademicYear
): TimelineItem[] => {
  const [startYear] = academicYear.split('-');
  const endYear = `20${academicYear.split('-')[1]}`;
  const items: TimelineItem[] = [];

  if (circumstances.divorcedParents || circumstances.remarriedParent) {
    items.push({
      id: `${academicYear}-sc-divorced`,
      date: `${startYear}-09-15`,
      title: 'Gather Parent/Contributor Information',
      description: 'Collect tax documents and financial information from the parent who will be the FAFSA contributor. This may be different from your custodial parent.',
      type: 'priority',
      priority: true,
    });
  }

  if (circumstances.independentStudent) {
    items.push({
      id: `${academicYear}-sc-independent`,
      date: `${startYear}-09-01`,
      title: 'Verify Independent Status',
      description: 'Review independent student criteria and gather documentation to support your independent status claim.',
      type: 'priority',
      priority: true,
    });
  }

  if (circumstances.specialCircumstances) {
    items.push({
      id: `${academicYear}-sc-special`,
      date: `${startYear}-10-15`,
      title: 'Document Special Circumstances',
      description: 'Gather documentation for special circumstances (job loss, medical expenses, etc.) that may affect your financial aid eligibility.',
      type: 'priority',
      priority: true,
    });
  }

  if (circumstances.appealPlanned) {
    items.push(
      {
        id: `${academicYear}-sc-appeal-prep`,
        date: `${endYear}-03-15`,
        title: 'Prepare Financial Aid Appeal',
        description: 'Begin preparing your financial aid appeal letter and supporting documentation. Contact your college\'s financial aid office for appeal procedures.',
        type: 'priority',
        priority: true,
      },
      {
        id: `${academicYear}-sc-appeal-submit`,
        date: `${endYear}-04-15`,
        title: 'Submit Financial Aid Appeal',
        description: 'Submit your financial aid appeal with all supporting documentation. Follow up with the financial aid office within 2 weeks.',
        type: 'deadline',
        priority: true,
      }
    );
  }

  return items;
};
